### ISSUE TITLE
PineTime Firmware Update via App

### ISSUE THREAD

**Issue by sn3kyJ3di** [xan-m/Infini-iOS#17]
Just received my watch and noticed it's running 1.2.1 and this app needs 1.3.1 at least.  Does the update via app work?  Any instructions?  Looks like it wants me to point to a file on my phone.  Can I just download the InfiniTime firmware from Pine64.com, unzip, and point to the file?

**Comment by xan-m** [comment]
Awesome, and welcome! You can grab the latest firmware zip file from the InfiniTime releases page here: https://github.com/JF002/InfiniTime/releases

As for flashing, just select the zip file (no need to unzip it) and start the transfer. The app will handle the unzip for you and send the file over to the watch. 

Let me know if you run into any trouble!

**Comment by sn3kyJ3di** [comment]
Firmware update worked perfectly.  Thank you, I have been looking at the PineTime for a while now and when I saw you started this app, I pulled the trigger.  Anything in particular you need tested?

**Comment by xan-m** [comment]
Aw thanks, glad to help! Just try everything on the app and let me know if anything doesn’t work the way you feel like it should.

If you ever experience a crash, send a crash report through TestFlight so I get the breakdown of what happened. It tells me exactly what caused the crash down to the line of code, so it makes it much easier to find and fix the bugs. 

Otherwise feel free to open new issues here with any bugs, UI suggestions, or feature requests! I’m extremely new to software development but I’ll try my best to add any features that people want.

**Comment by xan-m** [comment]
Looks like this is all resolved, I'm going to mark it as closed.
