### ISSUE TITLE
Xcode version incompatibility

### ISSUE THREAD

**Issue by stefanoaz** [xan-m/Infini-iOS#3]
This is not strictly a bug - more of a note. For those of us who are running something older than Big Sur (I'm running Catalina 10.15.7), the latest version of XCode I can run is 12.4 - and that will not accept an iPhone with iOS 14.6 as a target because it is too new. Unfortunately my Mac cannot run Big Sur, which is required for any later version of XCode.

**Comment by stefanoaz** [comment]
The iPhone runs iOS 14.6 and my XCode won't build for it. It does open the project, but notifies at build that the iOS version is unsupported.

The latest iOS version supported by XCode 12.4, is iOS 14.4. So if you made a fork for that I'd be happy to try it - thanks.

**Comment by xan-m** [comment]
Hmm, I don't think that this is a compatibility issue with this software. It sounds like the error message you're getting is an error between your phone and your version of XCode, and doesn't have anything to do with the source code.

As a test, can you try just building the project (Command-B) instead of selecting your phone as the build target? If the app builds okay on it's own then that confirms that it's not an issue with the source code, but rather an incompatibility between your phone and your version of XCode.

**Comment by stefanoaz** [comment]
I think that's correct - I would have to (somehow) revert my iPhone to the older iOS, for the build to be possible. I did try to build in precisely that way - selecting the phone as the target - and got the incompatibility notification. Since my iMac is too old to run a later XCode, I won't be able to build your code. I'm waiting for a desktop version of Apple's M1 ARM, before I upgrade my hardware... slapping an M1 into an iMac makes it look like an iPad on a stand - which - it is.

**Comment by xan-m** [comment]
Thanks for double checking for me and for closing the issue, and sorry about the incompatibility you're facing -- that's the worst of hardware frustrations. Hopefully the mac you're looking for comes out soon!

**Comment by xan-m** [comment]
@stefanoaz It just occurred to me that I probably should have reached out here to let you know that Infini-iOS is on TestFlight now, if you haven't had a chance to grab it, you should!
